apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: default
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
  - name: {{ .Values.name }} 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
---

