name: Deploy

on:
  push:
      branches: 
        - main
      paths:
        - 'src/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    if: ${{ github.repository == 'william-barros-costa/devops_portfolio' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          check-latest: true
      - name: Test
        run: |
          cd src
          go test ./...
      - name: Format
        run: |
          cd src
          go install golang.org/x/tools/cmd/goimports@latest
          go list -f {{.Dir}} ./... | xargs -I{} gofmt -w -s {}
          go list -f {{.Dir}} ./... | xargs -I{} goimports -w {}
          go mod tidy

  build-and-push-image:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      attestations: write 
      id-token: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: src
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
      
      - name: Update Helm Chart
        run: |
          sed -i 's/tag: .*/tag: ${{ github.sha }}/' helm/values.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Changed Helm Chart tag"

      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

